FROM python:3.8.7

ENV DATABASE_URL=postgres://postgres:ghqCj0bJWrLjjFpn@database-1.cby89z006voo.us-east-1.rds.amazonaws.com/database-1

RUN pip install pip --upgrade
RUN pip install pipenv

COPY . /app

WORKDIR /app

RUN pipenv install
# RUN ./run_app.sh

EXPOSE 5000

CMD ./run_app.sh